spring:
  datasource:
     url: jdbc:mysql://localhost:3306/bloy
     username: bloy
     password: bloy
     driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
server:
  port: 9008